---
Name: shorturl-config
Before:
  - '#oggle-config'
---
ShortURLModel:
  extensions:
    - ShortURLModelExtension
Page:
  extensions:
    - ShortURLPageExtension
Page_Controller:
  action: 'share'
  extensions:
    - ShortURLPageControllerExtension